name: Bug report
description: Use this template to report bugs or other issues affecting the project.
labels: bug

body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description of the issue, including any helpful context.
      placeholder: |
        Describe the issue here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please list the steps required to reproduce the issue.
      placeholder: |
        Example:
        1. Go to the Main tab.
        2. Open a video.
        3. Observe the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Crash log
      description: |
        **Do not paste crash log text here. Please attach a zipped `.ips` crash log file instead.**

        **To locate and attach your crash log:**
        1. Open **Settings** on your device.
        2. Go to **Privacy & Security** > **Analytics & Improvements** > **Analytics Data**.
        3. Find the log for the app. The file name usually begins with `YouTubeMusic_` followed by the date and time.
        4. Open the file, tap the **Share** icon, save it to the **Files** app, and then compress it into a `.zip` file.
        5. Attach the `.zip` file to this report.
      placeholder: |
        Drag and drop your Crashlog.zip file here.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Submission checklist
      description: |
        **Important:** Please review each item carefully before submitting.
      options:
        - label: I have confirmed that a similar issue has not already been reported.
          required: true
        - label: I have verified that this issue is relevant to the project and the version I am using.
          required: true
        - label: I have provided a clear description of the problem and completed all required fields.
          required: true
        - label: I did not answer truthfully to all of the above checkboxes.
          required: false
        - label: By submitting this issue, I confirm that I have completed all required fields and followed the guidelines. I understand that incomplete or inaccurate reports may be closed without review.
          required: true
