#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSInteger, YTAGClientID) {
    YTAGClientIDiOS = 0,                   // clientName "IOS"
    YTAGClientIDMediaConnect = 1,          // clientName "MEDIA_CONNECT_FRONTEND" — exposes itag 141 (AAC 256k Premium)
    YTAGClientIDTVEmbed = 2,               // clientName "TVHTML5_SIMPLY_EMBEDDED_PLAYER" — robust fallback, bypasses most gates
};

/// Represents a single adaptive format from YT's /player response.
@interface YTAGFormat : NSObject
@property (nonatomic, assign) NSInteger itag;
@property (nonatomic, copy)   NSString *url;
@property (nonatomic, copy)   NSString *mimeType;       // e.g. "video/mp4; codecs=\"avc1.64002A\""
@property (nonatomic, copy, nullable) NSString *codec;  // parsed out of mimeType, e.g. "avc1.64002A"
@property (nonatomic, copy, nullable) NSString *container; // "mp4" / "webm" / "m4a"
@property (nonatomic, assign) NSInteger width;          // 0 for audio
@property (nonatomic, assign) NSInteger height;         // 0 for audio
@property (nonatomic, assign) NSInteger fps;            // 0 for audio
@property (nonatomic, assign) NSInteger bitrate;
@property (nonatomic, assign) long long contentLength;  // clen param
@property (nonatomic, assign) NSTimeInterval duration;  // from approxDurationMs
@property (nonatomic, copy, nullable) NSString *qualityLabel; // "1080p60", "1080p60 Premium", etc.
@property (nonatomic, copy, nullable) NSString *audioQuality; // e.g. "AUDIO_QUALITY_MEDIUM"
@property (nonatomic, copy, nullable) NSString *audioTrackID; // YouTube's audio-track id when present
@property (nonatomic, copy, nullable) NSString *audioTrackName; // "English", "Spanish", "English descriptive", ...
@property (nonatomic, copy, nullable) NSString *audioLanguageCode; // "en", "es", ...
@property (nonatomic, assign) BOOL audioIsDefault;
@property (nonatomic, assign) BOOL audioIsDubbed;
@property (nonatomic, assign) BOOL isDRC;               // xtags=drc=1
@property (nonatomic, assign) BOOL isVideoOnly;         // true if mimeType starts with "video/"
@property (nonatomic, assign) BOOL isAudioOnly;         // true if mimeType starts with "audio/"
@end

/// A single caption track available for the video.
@interface YTAGCaptionTrack : NSObject
@property (nonatomic, copy)   NSString *baseURL;       // YT's timedtext endpoint; append &fmt=vtt for WebVTT
@property (nonatomic, copy)   NSString *languageCode;  // "en", "es", ...
@property (nonatomic, copy, nullable) NSString *displayName; // "English" / "Spanish (auto-generated)"
@property (nonatomic, assign) BOOL isAutoGenerated;    // kind == "asr"
@property (nonatomic, assign) BOOL isTranslated;       // synthetic tlang track generated from YT's translation list
@property (nonatomic, copy, nullable) NSString *sourceLanguageCode;
@end

/// Result envelope.
@interface YTAGExtractionResult : NSObject
@property (nonatomic, copy) NSString *videoID;
@property (nonatomic, copy, nullable) NSString *title;
@property (nonatomic, copy, nullable) NSString *author;
@property (nonatomic, copy, nullable) NSString *shortDescription;  // videoDetails.shortDescription (may be long)
@property (nonatomic, copy, nullable) NSString *thumbnailURL; // highest-res thumbnail
@property (nonatomic, assign) NSTimeInterval duration;
@property (nonatomic, copy) NSArray<YTAGFormat *> *formats;   // all adaptive formats
@property (nonatomic, copy) NSArray<YTAGCaptionTrack *> *captionTracks; // may be empty
// Convenience filtered arrays:
@property (nonatomic, readonly) NSArray<YTAGFormat *> *videoFormats;
@property (nonatomic, readonly) NSArray<YTAGFormat *> *audioFormats;
@end

typedef void (^YTAGExtractionCompletion)(YTAGExtractionResult * _Nullable result, NSError * _Nullable error);

@interface YTAGURLExtractor : NSObject

/// Async POST to /youtubei/v1/player. Completion fires on the main queue.
/// Use only if you don't have a live YTPlayerViewController — prefer `extractFromPlayerVC:`
/// which reads YT's already-resolved in-memory structures with zero network / spoofing.
+ (void)extractVideoID:(NSString *)videoID
              clientID:(YTAGClientID)clientID
            completion:(YTAGExtractionCompletion)completion;

/// Live-read path: walks `pvc.playerResponse.playerData.streamingData.adaptiveFormatsArray`
/// off the already-playing YTPlayerViewController. No network, no client spoofing.
/// This is exactly what YTLite's `-[DownloadMenuHelper getVideoFormatsArray:]` does
/// (decomp sub_361536 at 361570-361573).
/// Completion fires synchronously on the calling queue (usually main).
+ (nullable YTAGExtractionResult *)extractFromPlayerVC:(id)playerVC;

@end

NS_ASSUME_NONNULL_END
